### ISSUE TITLE
As a user, I want to receive some basic biographical facts about the celebrity in my photo

### ISSUE THREAD

**Issue by alabuda98** [nyu-software-engineering/profile-photo-lookup#10]
## Description
The user should be able to receive the name, official photo, and other basic biographical facts about the person such as gender, age, DOB.

## Estimation
L

## Acceptance Criteria 
- [ ] returns a name
- [ ] returns a clear headshot
- [ ] returns other basic biographical facts

**Comment by kayliokeefe** [comment]
Acceptance Criteria 
- [ ] User can upload a photo
- [ ] User receives name of the person in their photo
- [ ] Based on the type of celebrity, users will receive relevant information about the person in their search picture
